### ISSUE TITLE
Traffic reduction coefficient not saved

### ISSUE THREAD

**Issue by toverux** [tduck973564/TrafficSimulationAdjuster#1]
Hi, thanks for that mod, indispensable for us who like to play with dense areas and have additional challenge.

I noticed that the reduction coefficient value was not saved upon restarting the game. While sometimes options of other mods are also reset (maybe due to version changes and PDX mods instability), this is systematic for TrafficSimulationAdjuster, making me think there's something wrong with this one in particular.

Do you know about the issue?
In any case, I'd be happy to help if you want more info.

Cheers!

**Comment by khallmark** [comment]
I've opened a pull request to resolve the issue but its up to the maintainer to push a new version. Cheers.

**Comment by fesdonomist** [comment]
Still occurs, I think I know why 

I'm storing the value in a private field that doesn't have the attribute of the public one, so I don't think the game actually thinks it's a setting that should be saved, instead saving the public field which is really just a getter and setter

**Comment by khallmark** [comment]
Hmm. The UI looks right but I guess it's not actually lowering the coeff?

**Comment by fesdonomist** [comment]
> Hmm. The UI looks right but I guess it's not actually lowering the coeff?
> 

It's lowering it, it's just not saving the value because the value that's actually registered as a saveable setting in the game is literally just a setter for the private field that the game doesn't record

This shouldn't be too difficult for me to fix, I can do it today if I get time

**Comment by fesdonomist** [comment]
Fixed by [23c7187](https://github.com/tduck973564/TrafficSimulationAdjuster/commit/23c71879dc8d76dc5fa19f2fdcf4cc133f1268b9)

**Comment by fesdonomist** [comment]
For anyone else having this issue, I wasn't loading the settings file in the first place. You need to put `AssetDatabase.global.LoadSettings(nameof(TrafficSimulationAdjuster), Options, new TrafficSimulationAdjusterOptions(this));` in `OnLoad();`
